# This is a basic workflow to help you get started with Actions

name: Solidity CI and Security Static Scan

# Controls when the workflow will run
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - release*/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      commit_url: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}/

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Setup Python
      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@v2

#       # Cache PIP
#       - name: Cache PIP
#         id: python-cache
#         uses: actions/cache@v2
#         with:
#           path: ~/.local/share/virtualenvs
#           key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-pipenv-${{ hashFiles('Pipfile.lock') }}
          
      # Install dependencies
      - name: Install dependencies
        run: yarn
  
      - name: Install Slither
#         if: steps.python-cache.outputs.cache-hit != 'true'
        run: |
          python3 -m pip install --upgrade pip
          pip install slither-analyzer
      
      - name: Artifact build
        run: yarn compile

      - name: Unit-Test Contracts
        run: yarn test
        
      - name: slither-analyzer
        run: |
          slither . --ignore-compile --sarif slither.sarif --filter-paths "hardhat" --checklist --markdown-root ${{ env.commit_url }} > ./report.md  || true

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: "slither.sarif"

      - name: Render template
        id: template
        uses: chuhlomin/render-template@v1.4
        with:
          template: ./report.md

      - name: Create comment
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.number }}
          body: ${{ steps.template.outputs.result }}
